import type {Env,Locale,Source} from "../types";
type Story={title:string;summary:string;url:string;publisher:string;publishedAt?:string;imageUrl?:string;imageAlt?:string};
const feeds=(lang:Locale)=>lang==="ar"
?[["BBC Arabic","https://feeds.bbci.co.uk/arabic/rss.xml"],["Al Jazeera Arabic","https://www.aljazeera.net/aljazeera/rss"],["DW Arabic","https://rss.dw.com/rdf/rss-ar-all"],["France 24 Arabic","https://www.france24.com/ar/rss"],["Sky News Arabia","https://www.skynewsarabia.com/rss"]]
:[["BBC","https://feeds.bbci.co.uk/news/rss.xml"],["Al Jazeera","https://www.aljazeera.com/xml/rss/all.xml"],["DW","https://rss.dw.com/rdf/rss-en-all"],["France 24","https://www.france24.com/en/rss"],["The Guardian","https://www.theguardian.com/world/rss"]];
const esc=(s:string)=>s.replace(/<!\[CDATA\[([\s\S]*?)\]\]>/g,"$1").replace(/<[^>]+>/g," ").replace(/&amp;/g,"&").replace(/&quot;/g,'"').replace(/&#39;/g,"'").replace(/&#x27;/g,"'").replace(/\s+/g," ").trim();
const readFeed=async(name:string,url:string):Promise<Story[]>=>{try{const c=new AbortController();const t=setTimeout(()=>c.abort(),5000);const r=await fetch(url,{signal:c.signal,headers:{accept:"application/rss+xml, application/xml, text/xml"}});clearTimeout(t);if(!r.ok)return[];const x=await r.text();return[...x.matchAll(/<item[\s\S]*?<\/item>/gi)].slice(0,12).map(m=>{const z=m[0],tag=(n:string)=>esc(z.match(new RegExp("<"+n+"[^>]*>([\\s\\S]*?)<\\/"+n+">","i"))?.[1]||"");const image=z.match(/<(?:media:content|media:thumbnail|enclosure)[^>]+url=["']([^"']+)["']/i)?.[1];return{title:tag("title"),summary:tag("description").slice(0,1000),url:tag("link"),publisher:name,publishedAt:tag("pubDate"),imageUrl:image,imageAlt:tag("title")}}).filter(s=>s.title&&s.url)}catch{return[]}};
async function sourceImage(url:string):Promise<string|undefined>{try{const r=await fetch(url,{signal:AbortSignal.timeout(2500),headers:{accept:"text/html"}});if(!r.ok)return;const h=await r.text();return h.match(/<meta[^>]+property=["']og:image["'][^>]+content=["']([^"']+)["']/i)?.[1]||h.match(/<meta[^>]+content=["']([^"']+)["'][^>]+property=["']og:image["']/i)?.[1]}catch{return}}
const terms=(s:string)=>s.toLowerCase().replace(/[^\p{L}\p{N}]+/gu," ").split(/\s+/).filter(x=>x.length>2);
async function wikimediaImage(query:string):Promise<string|undefined>{try{const u="https://commons.wikimedia.org/w/api.php?action=query&generator=search&gsrsearch="+encodeURIComponent(query)+"&gsrnamespace=6&gsrlimit=8&prop=imageinfo&iiprop=url|extmetadata&iiurlwidth=1200&format=json&origin=*";const r=await fetch(u,{signal:AbortSignal.timeout(3500),headers:{accept:"application/json"}});if(!r.ok)return;const d=await r.json<any>();const pages=Object.values(d.query?.pages||{}) as any[];const q=terms(query);let best:any;let bestScore=0;for(const p of pages){const name=String(p.title||"");const info=p.imageinfo?.[0];const hay=terms(name+" "+(info?.extmetadata?.ImageDescription?.value||"")).join(" ");const hit=q.filter(t=>hay.includes(t)).length;const score=q.length?hit/q.length:0;if(score>bestScore){bestScore=score;best=info}}return bestScore>=0.45?(best?.thumburl||best?.url):undefined}catch{return}}
export async function news(env:Env,lang:Locale){
 const fs=feeds(lang); const batches=await Promise.all(fs.map(([n,u])=>readFeed(n,u))); const all=batches.flat();
 const seen=new Set<string>(); const unique=all.filter(s=>{const k=s.title.toLowerCase().replace(/[^\p{L}\p{N}]+/gu," ").trim();if(seen.has(k))return false;seen.add(k);return true}).slice(0,Math.max(6,Math.min(40,Number((await env.DB.prepare("SELECT value FROM admin_settings WHERE key=?").bind("news_items").first<any>())?.value||24))));
 const enriched=await Promise.all(unique.map(async s=>{if(s.imageUrl)return s; const direct=await sourceImage(s.url); if(direct)return {...s,imageUrl:direct}; const img=await wikimediaImage(s.title+" "+s.summary); return img?{...s,imageUrl:img}:s;}));
 return {ok:enriched.length>0,providers:fs.map(x=>x[0]),items:enriched.map(s=>({title:s.title,summary:s.summary,url:s.url,publisher:s.publisher,publishedAt:s.publishedAt,imageUrl:s.imageUrl,imageAlt:s.imageAlt||s.title,sources:[{title:s.title,publisher:s.publisher,url:s.url,publishedAt:s.publishedAt,imageUrl:s.imageUrl} as Source],evidence:"mixed" as const}))};
}
