import type{Env,Lang,Article}from"./types";
export async function articles(env:Env,lang:Lang,section?:string){let q="SELECT * FROM articles WHERE lang=? AND status='published'";const a:any[]=[lang];if(section){q+=" AND section=?";a.push(section)}q+=" ORDER BY published_at DESC LIMIT 50";return((await env.DB.prepare(q).bind(...a).all()).results||[]) as Article[]}
export async function article(env:Env,slug:string,lang:Lang){return await env.DB.prepare("SELECT * FROM articles WHERE slug=? AND lang=? AND status='published' LIMIT 1").bind(slug,lang).first<Article>()}
export async function event(env:Env,visitor:string,type:string,meta=""){await env.DB.prepare("INSERT INTO events(visitor,type,meta,created_at) VALUES(?,?,?,datetime('now'))").bind(visitor,type,meta).run()}
export async function contribute(env:Env,visitor:string,title:string,body:string,source:string){await env.DB.prepare("INSERT INTO contributions(visitor,title,body,source,status,created_at) VALUES(?,?,?,?,?,datetime('now'))").bind(visitor,title,body,source,"pending").run()}
export async function save(env:Env,visitor:string,slug:string){await env.DB.prepare("INSERT OR IGNORE INTO saved(visitor,slug,created_at) VALUES(?,?,datetime('now'))").bind(visitor,slug).run()}
export async function unsave(env:Env,visitor:string,slug:string){await env.DB.prepare("DELETE FROM saved WHERE visitor=? AND slug=?").bind(visitor,slug).run()}
export async function saved(env:Env,visitor:string,lang:Lang){return((await env.DB.prepare("SELECT a.* FROM articles a JOIN saved s ON s.slug=a.slug WHERE s.visitor=? AND a.lang=? ORDER BY s.created_at DESC").bind(visitor,lang).all()).results||[]) as Article[]}
export async function trending(env:Env){return(await env.DB.prepare("SELECT type,COUNT(*) count FROM events WHERE created_at>=datetime('now','-24 hours') GROUP BY type ORDER BY count DESC LIMIT 20").all()).results||[]}
