import{Env,json,admin,unauthorized,clean,now}from"./core";import{news}from"./news";import{answer}from"./ai";import{getNews,getArticle,searchArticles,analytics,contribute,adminContributions,adminAnalytics}from"./db";import{weather,fx}from"./live";import{telegram}from"./notify";
const visitor=(req:Request)=>req.headers.get("x-bayan-visitor")?.slice(0,100)||"anonymous";
const lang=(u:URL)=>u.searchParams.get("lang")==="en"?"en":"ar";
export async function api(req:Request,env:Env,url:URL){const p=url.pathname,L=lang(url);
if(p==="/api/health"||p==="/health")return json({ok:true,version:env.BAYAN_VERSION||"2.0.0",commit:env.BAYAN_COMMIT_SHA||null,time:now()});
if(p==="/api/weather")return json({ok:true,data:await weather()});
if(p==="/api/fx")return json({ok:true,data:await fx()});
if(p==="/api/news"){const items=await news(env);return json({ok:true,items:items.filter((x:any)=>!x.language||x.language===L),providers:["Al Jazeera RSS","BBC Arabic RSS","Google News RSS"],updatedAt:now()})}
if(p==="/api/article"){const item=await getArticle(env,clean(url.searchParams.get("slug"),300));return item?json({ok:true,item}):json({ok:false,error:"not_found"},404)}
if(p==="/api/search"){const q=clean(url.searchParams.get("q"),500);if(!q)return json({ok:false,error:"missing_query"},400);const results=await searchArticles(env,q,L,30);await analytics(env,visitor(req),"search","/search",L,q);return json({ok:true,query:q,language:L,results,sources:results.flatMap((x:any)=>x.sources||[]).slice(0,30)})}
if(p==="/api/ask"){const q=clean(url.searchParams.get("q"),1000);if(!q)return json({ok:false,error:"missing_query"},400);const evidence=await searchArticles(env,q,L,12);await analytics(env,visitor(req),"ask","/ai",L,q);if(evidence.length<1)return json({ok:true,query:q,answer:L==="en"?"Insufficient Evidence: BAYAN could not find enough published evidence to answer this question.":"أدلة غير كافية: لم يجد بيان معلومات منشورة موثوقة كافية للإجابة.",sufficient:false,sources:[]});return json({ok:true,query:q,language:L,...await answer(env,q,evidence)})}
if(p==="/api/contribute"&&req.method==="POST"){const b=await req.json().catch(()=>({})) as any;const title=clean(b.title,300),body=clean(b.body,8000);if(!title||!body)return json({ok:false,error:"invalid"},400);await contribute(env,{title,body,source:clean(b.source,1000)});await telegram(env,"BAYAN contribution pending review: "+title);return json({ok:true,review:"pending"})}
if(p==="/api/sitemap")return json({ok:true,items:await getNews(env,500,L)});
if(p.startsWith("/api/admin/")){if(!admin(req,env))return unauthorized();if(p==="/api/admin/news")return json({ok:true,items:await getNews(env,100,L)});if(p==="/api/admin/contributions")return json({ok:true,items:await adminContributions(env)});if(p==="/api/admin/analytics")return json({ok:true,data:await adminAnalytics(env)});if(p==="/api/admin/telegram"&&req.method==="POST"){const b=await req.json().catch(()=>({}));return json({ok:await telegram(env,clean((b as any).message,3500))})}return json({ok:true})}
return json({ok:false,error:"not_found"},404)}
