import type {Locale} from "./types";

const wisdom:Record<string,{ar:string[];en:string[]}>={
  egypt:{ar:["المعلومة المحلية تصبح أقوى حين نعرف مصدرها وزمنها.","ما يهم الناس يبدأ من تفاصيل الحياة اليومية.","الخبر المفيد لا يكتفي بما حدث؛ يوضح لماذا يهم."],en:["Local knowledge gets stronger when its source and timing are clear.","What matters to people often starts with everyday details.","Useful news does more than say what happened; it explains why it matters."]},
  arab:{ar:["فهم المنطقة يحتاج إلى أكثر من عنوان واحد.","السياق يغيّر معنى الخبر.","مقارنة الروايات تكشف ما تثبته الأدلة وما لا تثبته."],en:["Understanding a region takes more than one headline.","Context can change the meaning of a story.","Comparing accounts shows what the evidence does and does not establish."]},
  world:{ar:["العالم مترابط؛ خبر بعيد قد يصنع أثرًا قريبًا.","السرعة لا تعني دائمًا الدقة.","كل حدث كبير يحتاج إلى سياق قبل الحكم عليه."],en:["The world is connected; a distant event can create a local effect.","Speed does not always mean accuracy.","Every major event needs context before judgment."]},
  science:{ar:["السؤال الجيد بداية المعرفة، والدليل هو ما يختبرها.","الاكتشاف لا يصبح حقيقة لمجرد انتشاره.","النتيجة العلمية أقوى عندما يمكن فحص طريقتها ومصدرها."],en:["A good question starts knowledge; evidence tests it.","A discovery is not a fact simply because it spreads.","Scientific findings are stronger when their method and source can be examined."]},
  economy:{ar:["الرقم بلا تاريخ ووحدة وسياق قد يضلل.","الأسعار تتغير، لذلك الزمن جزء من المعلومة.","فهم الاقتصاد يبدأ بتمييز الخبر عن التوقع."],en:["A number without a date, unit and context can mislead.","Prices change, so time is part of the information.","Understanding economics starts by separating news from forecasts."]},
  politics:{ar:["الادعاء السياسي يحتاج إلى مصدر مستقل قبل أن يصبح حقيقة.","القرار أهم حين نفهم نصه وأثره لا عنوانه فقط.","الخلاف في السياسة لا يلغي ضرورة التحقق من الوقائع."],en:["A political claim needs independent evidence before it becomes a fact.","A decision matters more when its text and impact are understood, not just its headline.","Political disagreement does not remove the need to verify facts."]},
  technology:{ar:["التقنية أداة؛ قيمتها في ما تحله لا في ضجيجها.","الذكاء الاصطناعي يساعد في العمل، لكنه لا يلغي التحقق.","الميزة الجديدة لا تعني بالضرورة نتيجة أفضل."],en:["Technology is a tool; its value lies in what it solves.","AI can assist work, but it does not remove the need to verify.","A new feature does not necessarily mean a better outcome."]},
  health:{ar:["المعلومة الصحية الجيدة تذكر حدود الدليل.","ليس كل ما ينتشر نصيحة طبية.","في الصحة، مصدر موثوق أهم من عنوان مثير."],en:["Good health information makes the limits of evidence clear.","Not everything that spreads is medical advice.","In health, a reliable source matters more than a dramatic headline."]},
  history:{ar:["الماضي لا يتغير، لكن فهمه يتطور مع ظهور الأدلة.","التاريخ يحتاج إلى مصدر وسياق، لا إلى حكاية واحدة.","ما بقي من الماضي قد يخبرنا بقدر ما فُقد منه."],en:["The past does not change, but our understanding can improve as evidence appears.","History needs sources and context, not a single story.","What survives from the past can tell us as much as what was lost."]},
  people:{ar:["الشخصية تُفهم من أفعالها الموثقة لا من الصورة المتداولة عنها.","السيرة الجيدة تفرق بين الحقيقة والانطباع.","الإنجاز يصبح أوضح عندما نعرف زمنه ومصدره."],en:["A person is understood through documented actions, not just their public image.","A good biography separates fact from impression.","An achievement becomes clearer when its date and source are known."]},
  sports:{ar:["الأرقام الرياضية تحتاج إلى سياق قبل المقارنة.","النتيجة لحظة؛ السجل قصة أطول.","الإحصاء الجيد يشرح الأداء بدل أن يستبدل القصة برقم."],en:["Sports numbers need context before comparison.","A result is a moment; a record is a longer story.","Good statistics explain performance rather than replacing the story with a number."]},
  travel:{ar:["الرحلة الأفضل تبدأ بمعلومة حديثة.","الوجهة الجميلة لا تكفي إذا كانت القواعد غير واضحة.","تفاصيل صغيرة في السفر قد تصنع فرقًا كبيرًا."],en:["A better trip starts with current information.","A beautiful destination is not enough if the rules are unclear.","Small travel details can make a big difference."]},
  trends:{ar:["الانتشار دليل على الاهتمام، وليس دليلًا على صحة الادعاء.","الترند إشارة تستحق الفحص، لا حكمًا نهائيًا.","قبل مشاركة الرائج، ابحث عن أصله وتاريخه."],en:["Popularity signals interest, not truth.","A trend is a signal worth checking, not a final verdict.","Before sharing what is trending, check its origin and date."]},
  prices:{ar:["الرقم الحي له قيمة حين نعرف مصدره ووقت تحديثه.","قارن الأرقام على أساس واحد قبل اتخاذ القرار.","البيانات تتكلم أفضل عندما نعرف كيف جُمعت."],en:["Live numbers matter more when their source and update time are clear.","Compare figures on the same basis before deciding.","Data speaks more clearly when we know how it was collected."]}
};

export function wisdomFor(section:string,language:Locale){
  const set=wisdom[section]||wisdom.world;
  const items=set[language]||set.ar;
  const index=Math.floor(Date.now()/1000/60/60)%items.length;
  return items[index];
}
